name: Native Image
on:
  release:
    types: [published]

jobs:
  native-image:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm]
        include:
          - os: ubuntu-latest
            uploaded_filename: todo-backend-linux-amd64
            local_path: build/native/nativeCompile/todo-backend
          - os: ubuntu-24.04-arm
            uploaded_filename: todo-backend-linux-arm64
            local_path: build/native/nativeCompile/todo-backend
    steps:
      - uses: actions/checkout@v5

      - uses: graalvm/setup-graalvm@v1
        with:
          java-version: '25'
          distribution: 'graalvm'
          native-image-job-reports: 'true'

      - name: Native Image Linux
        run: ./gradlew nativeCompile
        shell: bash

      - uses: actions/upload-artifact@v4
        with:
          path: ${{ matrix.local_path }}
          name: ${{ matrix.uploaded_filename }}
