name: Native Image
on:
  release:
    types: [published]

jobs:
  native-image:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm]
        include:
          - os: ubuntu-latest
            uploaded_filename: todo-backend-linux-amd64
            local_path: build/native-image/todo-backend
          - os: ubuntu-24.04-arm
            uploaded_filename: todo-backend-linux-arm64
            local_path: build/native-image/todo-backend
    steps:
      - uses: actions/checkout@v5
      - name: Set up JDK 24
        uses: actions/setup-java@v5
        with:
          java-version: |
            24
            23
          distribution: temurin
          cache: gradle

      - name: Native Image Linux amd64
        run: ./gradlew nativeImage
        shell: bash

      - uses: actions/upload-artifact@v4
        with:
          path: ${{ matrix.local_path }}
          name: ${{ matrix.uploaded_filename }}
